baseurl = "https://forcode.jp/"
languageCode = "ja"
DefaultContentLanguage = "ja"
theme = "hello-friend"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "blog"
  # "light" or "dark"
  defaultTheme = "dark"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 5
  # Show reading time in minutes for posts
  showReadingTime = true

[languages]
  [languages.ja]
    languageName = "Japanese"
    title = "FORCODE"
    subtitle = "Go for code, Run for code."
    keywords = "プログラミング, 学習, 評価, 評価制度"
    copyright = "© Forcode Co., Ltd."
    readMore = "続きを読む"
    readOtherPosts = "Read other posts"

    [languages.ja.params.logo]
      logoText = "#!/usr/bin/env forcode"
      logoHomeLink = "/"

    [languages.ja.menu]
      [[languages.ja.menu.main]]
        identifier = "about"
        name = "Hello, Forcode!"
        url = "/blog/hello-forcode/"
